### ISSUE TITLE
No module named 'register_files_to_profile'

### ISSUE THREAD

**Issue by HansBambel** [plasma-umass/scalene#273] opened 2021-09-28 06:47 UTC
**Describe the bug**
I installed the latest version of Scalene using `python3 -m pip install -U git+https://github.com/plasma-umass/scalene.git` as was advised in #110 in order to get rid of a SIGSEGV error.

When running `scalene -m my-script.py` I receive the following error:
```
Scalene failed to initialize.
Traceback (most recent call last):
  File "/Users/Hans/opt/anaconda3/envs/ai-models/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 1433, in run_profiler
    import register_files_to_profile
ModuleNotFoundError: No module named 'register_files_to_profile'
``` 

I managed to get the profiler working by using the `cpu-only` flag:
`scalene --cpu-only -m my-script.py`

I am assuming scalene wants to use the "GPU" of the M1 chip?

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Chip: M1

**Comment by jaltmayerpizzorno** [comment] 2021-09-28 18:09
This is an issue loading `libscalene.dylib`, which is required for memory and memcpy profiling but not for CPU profiling. It has nothing to do with a built-in GPU (our GPU support is for NVIDIA GPUs). I'm on it...

**Comment by jaltmayerpizzorno** [comment] 2021-10-02 13:37
We're almost there... our next release should fix it. BTW, the problem is anaconda specific (and stems from their static linking of the Python library).

**Comment by HansBambel** [comment] 2021-10-04 05:46
Great, thanks for fixing!

**Comment by jaltmayerpizzorno** [comment] 2021-10-04 11:46
It should be fixed on github now, and I expect we'll release to pypi soon. Please re-open if it doesn't work.

**Closed by jaltmayerpizzorno** 2021-10-04 11:46 UTC
