### ISSUE TITLE
Scalene: internal error = 28 (src/include/samplefile.hpp:108)

### ISSUE THREAD

**Issue by ktalik** [plasma-umass/scalene#545] opened 2023-01-12 20:00 UTC
**Describe the bug**
When I run the example python file with scalene I get internal error = 28

**To Reproduce**
1. Create `test.py` file with

   ```py
   def slow_function():
        import time
        time.sleep(3)

   ```
3. Run `scalene test.py` or `poetry run scalene test.py`
4. Error:

        Scalene: internal error = 28 (src/include/samplefile.hpp:108)
        Scalene error: received signal SIGABRT

**Expected behavior**
Profile

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: GNU/Linux 4.14.271 Manjaro
 - Version: 1.5.19 and 1.5.18

If you have not yet tried with the repository version (`python3 -m pip install git+https://github.com/plasma-umass/scalene`), please try that before reporting.

Installing from repo resulted with error:

```
$ python3 -m pip install git+https://github.com/plasma-umass/scalene
Collecting git+https://github.com/plasma-umass/scalene
  Cloning https://github.com/plasma-umass/scalene to /var/tmp/pip-req-build-bszj8fhi
  Running command git clone --filter=blob:none --quiet https://github.com/plasma-umass/scalene /var/tmp/pip-req-build-bszj8fhi
  Resolved https://github.com/plasma-umass/scalene to commit 554a7e7d32375f3da973700b744fa6b1d773bc8b
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      /home/konrad/.cache/pypoetry/virtualenvs/inbox-IttK0j-Y-py3.10/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running egg_info
      make vendor-deps
      rm -fr vendor/
      mkdir -p vendor && cd vendor && git clone https://github.com/emeryberger/Heap-Layers
      Klonowanie do „Heap-Layers”...
      mkdir -p vendor && cd vendor && git clone https://github.com/mpaland/printf
      Klonowanie do „printf”...
      cd vendor/printf && ln -s printf.c printf.cpp
      sed -e 's/^#define printf printf_/\/\/&/' vendor/printf/printf.h > /tmp/printf.h.$ && mv /tmp/printf.h.$ vendor/printf/printf.h
      sed: couldn't write 1 item to stdout: Brak miejsca na urządzeniu
      make: *** [GNUmakefile:62: vendor/printf/printf.cpp] Błąd 4
      error: command '/usr/bin/make' failed with exit code 2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```

**Additional context**
I used Scalene 1.5.18 and it was working very well, and producing useful profiles.
Then I upgraded to Scalene 1.5.19 and it stopped working.
After I rolled it back to 1.5.18 it didn't seem to work any longer as well.

**Comment by ktalik** [comment] 2023-01-12 20:03
OK, the `if you have not yet tried with the repository version` seems to be very useful, because during my install I can see:

```
      sed: couldn't write 1 item to stdout: Brak miejsca na urządzeniu
```

which means `no space left on device`.

I've checked my `/tmp` directory and there seem to be many big scalene files. How to remove them after each runtime...?

```
$ ls -lh /tmp
(redacted)
-rw------- 1 konrad konrad 256M Jan 12 18:51  scalene-memcpy-signal65493
-rw------- 1 konrad konrad 256M Jan 12 18:51  scalene-memcpy-signal65498
-rw------- 1 konrad konrad 256M Jan 12 18:53  scalene-memcpy-signal65789
-rw------- 1 konrad konrad 256M Jan 12 18:53  scalene-memcpy-signal65794
-rw------- 1 konrad konrad 256M Jan 12 18:54  scalene-memcpy-signal65934
-rw------- 1 konrad konrad 256M Jan 12 18:54  scalene-memcpy-signal65946
-rw------- 1 konrad konrad 256M Jan 12 18:54  scalene-memcpy-signal66082
-rw------- 1 konrad konrad 256M Jan 12 18:54  scalene-memcpy-signal66096
-rw------- 1 konrad konrad 256M Jan 12 18:55  scalene-memcpy-signal66652
-rw------- 1 konrad konrad 256M Jan 12 18:55  scalene-memcpy-signal66658
-rw------- 1 konrad konrad 256M Jan 12 18:56  scalene-memcpy-signal66804
-rw------- 1 konrad konrad 256M Jan 12 18:56  scalene-memcpy-signal66809
-rw------- 1 konrad konrad 256M Jan 12 18:59  scalene-memcpy-signal67184
-rw------- 1 konrad konrad 256M Jan 12 18:59  scalene-memcpy-signal67189
-rw------- 1 konrad konrad 256M Jan 12 19:00  scalene-memcpy-signal67335
-rw------- 1 konrad konrad 256M Jan 12 19:00  scalene-memcpy-signal67340
-rw------- 1 konrad konrad 256M Jan 12 19:15  scalene-memcpy-signal69552
-rw------- 1 konrad konrad 256M Jan 12 19:15  scalene-memcpy-signal69559
-rw------- 1 konrad konrad 256M Jan 12 19:16  scalene-memcpy-signal69718
-rw------- 1 konrad konrad 256M Jan 12 19:16  scalene-memcpy-signal69723
-rw------- 1 konrad konrad 256M Jan 12 19:17  scalene-memcpy-signal70427
-rw------- 1 konrad konrad 256M Jan 12 19:17  scalene-memcpy-signal70454
-rw------- 1 konrad konrad 256M Jan 12 19:21  scalene-memcpy-signal70981
-rw------- 1 konrad konrad 256M Jan 12 19:21  scalene-memcpy-signal70986
-rw------- 1 konrad konrad 256M Jan 12 19:23  scalene-memcpy-signal71278
-rw------- 1 konrad konrad 256M Jan 12 19:23  scalene-memcpy-signal71292
-rw------- 1 konrad konrad 256M Jan 12 19:26  scalene-memcpy-signal71694
-rw------- 1 konrad konrad 256M Jan 12 19:26  scalene-memcpy-signal71701
-rw------- 1 konrad konrad 256M Jan 12 19:34  scalene-memcpy-signal72618
-rw------- 1 konrad konrad 256M Jan 12 19:34  scalene-memcpy-signal72628
-rw------- 1 konrad konrad 256M Jan 12 19:35  scalene-memcpy-signal72747
-rw------- 1 konrad konrad 256M Jan 12 19:35  scalene-memcpy-signal72752
(redacted)
```

**Comment by ktalik** [comment] 2023-01-12 20:04
I've tried now, and it works fine after I removed those files. How to remove them after each `scalene` command?

**Comment by emeryberger** [comment] 2023-01-28 14:34
In theory, Scalene cleans these up after every execution. Can you verify that it is still leaving these behind? Thanks.

**Comment by ktalik** [comment] 2023-02-05 13:20
What do you mean by *still leaving behind*?

In my example, I've demonstrated how scalene is leaving those files after runtime. Each time I am running it again it is still not cleaning them.

**Comment by emeryberger** [comment] 2023-02-06 19:58
I couldn't reproduce the problem on my Mac, which is why I asked. However, I _was_ able to reproduce this on Fedora. The fix is now in the repository - please try that version and let me know. Thanks.

**Comment by emeryberger** [comment] 2023-02-06 22:48
Closing since fixed on my end; will re-open if it has not solved the reported problem.

**Closed by emeryberger** 2023-02-06 22:48 UTC
