### ISSUE TITLE
Scalene Memory Leak Detection fails to detect easy to reproduce memory leak

### ISSUE THREAD

**Issue by atw1020** [plasma-umass/scalene#313] opened 2022-01-07 04:58 UTC
**Describe the bug**

Scalene's Memory Leak detection cannot detect a simple memory leak caused by smart pointer ownership loops. Scalene reports that the program's memory profile is a constant 100% with no growth, even though the program is leaking memory.

**To Reproduce**

1. Implement the following memory leak in C++

```cpp
#include <string>
#include <memory>

struct B;

struct A{

    explicit A(const std::string& value){
        this->value = value;
    }

    std::shared_ptr<B> instanceB;
    std::string value;
};

struct B{

    explicit B(const std::string& value){
        this->value = value;
    }

    std::shared_ptr<A> instanceA;
    std::string value;
};

void leak(const std::string& string){
    auto a = std::make_shared<A>(string);
    auto b = std::make_shared<B>(string);
    a->instanceB = b;
    b->instanceA = a;
}
```

2. Map the ``leak`` function into python.
3. Write a python program that uses the ``leak`` function in a loop.

```py
import leaky_module
import tqdm

for i in tqdm.trange(10000000):  # this many iterations is maybe extreme
        leaky_module.leak("I want to run\nI want to hide\nI want to tear down the walls and hold the inside")
```

4. Run scalene on this program.

**Expected behavior**

The Program's Memory usage timeline records a constantly increasing memory usage profile during program execution and
reports the memory leak to the user.

**Screenshots**
<img width="1379" alt="Screen Shot 2022-01-06 at 8 52 54 PM" src="https://user-images.githubusercontent.com/50496947/148493765-04c6ec80-3668-407e-9edf-9d58c97ffdf6.png">

**Desktop (please complete the following information):**
 - OS: macOS Monteray 12.1 
 - Python: 3.8.10
 - Scalene: 1.3.16

**Additional context**

This problem might be related to the rate at which scalene samples memory usage. The uniform 100% memory usage that Scalene reports suggest to me that scalene only takes one sample of memory usage throughout the entire execution of the program since we know that the memory is not all allocated at once.

**Comment by emeryberger** [comment] 2022-01-08 01:20
Please install from the repo (`python3 -m pip install git+https://github.com/plasma-umass/scalene`) and try again. I built a module invoking your leak code, verified that it leaks by watching the rsize go up in `top`, and then ran it with Scalene. It reports massive growth. You can see that the growth rate is now correctly reported as high for the overall program (the number should be . In fact, if you run it with `--memory-leak-detector` (an experimental feature), it pinpoints the offending line.

                                                          Memory usage: ███████████████ (max:   3.02GB, growth rate: 113%)                                                      
                                                                 test-leaky.py: % of time =  99.67% out of   3.85s.                                                             
            ╷       ╷       ╷       ╷        ╷       ╷               ╷       ╷                                                                                                  
       Line │Time   │–––––– │–––––– │Memory  │–––––– │–––––––––––    │Copy   │                                                                                                  
            │Python │native │system │Python  │peak   │timeline/%     │(MB/s) │test-leaky.py                                                                                     
     ╺━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━━┿━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸
          1 │       │       │       │        │       │               │       │import leak                                                                                       
          2 │       │       │       │        │       │               │       │                                                                                                  
          3 │    6% │    1% │       │        │       │               │    70 │for i in range(10000000):                                                                         
          4 │   70% │   13% │   9%  │   6%   │    1M │█████▁▁▁▁ 100% │   508 │    leak.leak("I want to run\nI want to hide\nI want to tear down the walls and hold the inside"  
          5 │       │       │       │        │       │               │       │                                                                                                  
          6 │       │       │       │        │       │               │       │                                                                                                  
            ╵       ╵       ╵       ╵        ╵       ╵               ╵       ╵                                                                                                  
     Top AVERAGE memory consumption, by line:
     (1)     4:     1 MB                                                                                                                                                         
     Top PEAK memory consumption, by line:
     (1)     4:     1 MB                                                                                                                                                         
     Possible memory leak identified at line 4 (estimated likelihood: 100%, velocity:   0 MB/s)

Note that I agree the timelines are not as informative in this case as they could be - Scalene only stores a compressed representation of past memory allocations (otherwise, Scalene would itself "leak").

**Comment by emeryberger** [comment] 2022-01-08 17:56
For completeness, attached is a tarball of the files I created to run this test.
[leaky.tar.gz](https://github.com/plasma-umass/scalene/files/7833715/leaky.tar.gz)

**Comment by atw1020** [comment] 2022-01-08 19:50
Thank you, I've had a bit of trouble installing the GitHub clone but I haven't given it a real effort yet. I'll check your tarball when I get a chance.

**Comment by emeryberger** [comment] 2022-01-09 21:40
For now, I am closing this because I believe the issue is fixed. Please re-open if you find this not to be the case. Thanks!

**Closed by emeryberger** 2022-01-09 21:40 UTC

**Comment by emeryberger** [comment] 2022-01-14 21:55
@atw1020 you can now try this with the latest release (1.4.0).

**Comment by atw1020** [comment] 2022-01-14 22:56
Everything runs fine now, Thank you!
