### ISSUE TITLE
Scalene error: received signal SIGABRT

### ISSUE THREAD

**Issue by agigao** [plasma-umass/scalene#99] opened 2020-12-15 13:17 UTC
Hi there, first of all thanks for taking onto this serious issue of lack of proper profilers in Python world.

**Describe the bug**
The bug - I'm running CatBoost trainer and something is eating up 4gigs of ram during execution, although data size is 6 mb. I tried multiple profilers but haven't got any clue what's going on yet. Then I tried to run it with scalene, but it crashes with the following error:

    OSError: [Errno 24] Too many open files: '/home/server/.envs/anyml/lib/python3.8/site-packages/pygments/styles'
    SSScccaaallleeennneee:::   iiinnnttteeerrrnnnaaalll   eeerrrrrrooorr r=   9=
    =  99

and before that:

    catboost.CatBoostError: (Too many open files) util/system/file.cpp:831: can't open "catboost_info/learn/events.out.tfevents" 
    with mode WrOnly|CreateAlways|Seq (0x00000034)

**To Reproduce**
Not sure how can you reproduce the error, it runs perfectly well on a simple CatBoost example. And I can't share the code because of NDA :( 

**Expected behavior**
I expected to see what the heck is eating up my memory 😆

**Screenshots**
**mprof**
<img width="1137" alt="Screenshot 2020-12-15 at 17 12 11" src="https://user-images.githubusercontent.com/22436648/102219385-d4ec4e80-3ef8-11eb-9e5b-5258621bfcf3.png">
**pympler tracker**
<img width="875" alt="Screenshot 2020-12-15 at 16 06 25" src="https://user-images.githubusercontent.com/22436648/102219431-e7ff1e80-3ef8-11eb-9833-af8a408e2fa4.png">
**scalene**
<img width="789" alt="Screenshot 2020-12-15 at 17 16 54" src="https://user-images.githubusercontent.com/22436648/102219783-60fe7600-3ef9-11eb-9b06-512ed33139aa.png">

**Desktop (please complete the following information):**
 - OS: 
     OS: Manjaro 20.2 Nibia
     Kernel: x86_64 Linux 5.9.11-3-MANJARO
 Uptime: 3h 6m
 Packages: 1109
 Shell: bash 5.0.18
 Disk: 19G / 106G (18%)
 CPU: Intel Core i7-3770K @ 8x 3.9GHz [29.0°C]
 GPU: GeForce GTX 1070
 RAM: 1380MiB / 23996MiB

Cheers,  
Giga

**Comment by sternj** [comment] 2020-12-15 21:41
Is there any way you could construct a minimal example that also exhibits this same behavior? Is this impossible because there are also libraries that are under NDA?

**Comment by emeryberger** [comment] 2020-12-15 21:43
Also, can you indicate the version number of Scalene you are using, just in case? (If you haven't tried already, please do a `pip install -U scalene`). Thanks!

**Comment by gigch** [comment] 2020-12-16 12:40
Hey guys, thanks for response.

@sternj  Well, definitely not libraries, but I'll try to reproduce the error in a similar pipeline.

@emeryberger scalene is the latest version and installed w/ -U.

**Comment by emeryberger** [comment] 2021-03-14 17:00
Hi @gigch - please try the latest version and let us know what happens. If it still doesn't work, a repro case would of course help immensely.

**Comment by emeryberger** [comment] 2021-03-20 00:17
Just looked at the issue more closely, and definitely one of the bugs (the too many files issue) has been solved for some time.

**Comment by emeryberger** [comment] 2021-04-05 12:49
Closing as I believe the bug has been fixed; @gigch please re-open if not!

**Closed by emeryberger** 2021-04-05 12:49 UTC
