### ISSUE TITLE
Error handling command line arguments

### ISSUE THREAD

**Issue by josephlucas-arc** [plasma-umass/scalene#82] opened 2020-10-23 13:04 UTC
**Describe the bug**
When I run scalene on a script with arguments, I get a "Scalene: could not find input file" error.

**To Reproduce**
I have Scalene installed in a venv.
I can use it successfully on simple scripts.
I get reasonable output from `scalene train.py`, but the real use case I want to test is when I provide arguments to `train.py`.
`scalene train.py u training_data.csv` returns the listed error, but `python train.py u training_data.csv` runs as expected. 

**Expected behavior**
Scalene should profile the script with the provided command line arguments

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [WSL2]

**Additional context**

That aside, I'm super impressed with the tool!

**Comment by emeryberger** [comment] 2020-10-24 03:00
Can you indicate which version of `scalene` you are using? I was unable to reproduce this on WSL2 with a simple program (reproduced below, saved as `testargs.py`):

```
import sys
print(f"args = {len(sys.argv)}")
print(f"{sys.argv}")
```

Invoking `scalene testargs.py a b c` produces the same output as `python3 testargs.py a b c`, showing all arguments are being passed correctly. (If you could share your `train.py` source code, that would certainly help.)

**Comment by josephlucas-arc** [comment] 2020-10-27 11:33
Thanks for the quick reply.  I'd also tested with a toy example successfully, so it's probably on my end.
Here's the entry point
```
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=""
    )
    parser.add_argument(
        "learning_method",
        choices=["u", "unsupervised", "s", "supervised"],
        help="Learning type: 's'upervised or 'u'nsupervised",
    )
    parser.add_argument(
        "path", type=str, help="Path to csv containing training parameters"
    )
    parser.add_argument("--aws", dest='aws', action='store_true', help="NOT FUNCTIONAL: use if files in `path` are hosted on AWS")
    parser.add_argument("--err", default=0.05, type=float, help="goal error rate")
    args = parser.parse_args()
    if args.learning_method in ["s", "supervised"]:
        bulk_supervised(parse_supervised(args.path), args.aws)
    elif args.learning_method in ["u", "unsupervised"]:
        bulk_unsupervised(parse_unsupervised(args.path), args.aws, args.err)
    else:
        raise ValueError("Unrecognized learning_method")
```

Here's another thought.  I'm using joblib for some cheap parallelization (https://joblib.readthedocs.io/en/latest/parallel.html). Any potential impact there?  Thanks for the help!

**Comment by emeryberger** [comment] 2021-03-20 00:21
Should all be working fine now; closing.

**Closed by emeryberger** 2021-03-20 00:21 UTC
