### ISSUE TITLE
Scalene can't open browser on MacOS

### ISSUE THREAD

**Issue by isinyaaa** [plasma-umass/scalene#790] opened 2024-03-09 04:31 UTC
**Describe the bug**

Scalene fails to open the default web UI on MacOS, and when using the `--viewer` flag it throws

```raw
ERROR: Calling Scalene main function failed: 'MacOSXOSAScript' object has no attribute 'name'
Traceback (most recent call last):
  File "/Users/isinyaaa/Library/Caches/pypoetry/virtualenvs/superlesson-_GezG9T_-py3.10/lib/python3.10/site-packages/scalene/__main__.py", line 17, in main
    scalene_profiler.Scalene.main()
  File "/Users/isinyaaa/Library/Caches/pypoetry/virtualenvs/superlesson-_GezG9T_-py3.10/lib/python3.10/site-packages/scalene/scalene_profiler.py", line 1870, in main
    ) = ScaleneParseArgs.parse_args()
  File "/Users/isinyaaa/Library/Caches/pypoetry/virtualenvs/superlesson-_GezG9T_-py3.10/lib/python3.10/site-packages/scalene/scalene_parseargs.py", line 365, in parse_args
    if browser := find_browser():
  File "/Users/isinyaaa/Library/Caches/pypoetry/virtualenvs/superlesson-_GezG9T_-py3.10/lib/python3.10/site-packages/scalene/find_browser.py", line 15, in find_browser
    return browser.name if browser.name not in text_browsers else None
AttributeError: 'MacOSXOSAScript' object has no attribute 'name'
```

**To Reproduce**
1. Simply run `scalene --viewer`

**Expected behavior**
Scalene should open the web UI.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: ?

**Additional context**

I believe it was introduced in #779 as downgrading to 1.5.34 fixes the problem.

**Comment by emeryberger** [comment] 2024-03-10 00:36
Works for me. Please report the following:

Scalene version:
```bash
scalene --version
```

Mac OS version:
```bash
sw_vers
```

Python version:

```bash
python3 --version
```

**Comment by isinyaaa** [comment] 2024-03-10 01:19
I tried using scalene `>=1.5.35`. MacOS is `14.3.1` and python is `3.10.13`.

**Comment by emeryberger** [comment] 2024-03-10 19:02
Thanks! I was able to reproduce the issue with Python 3.10.13; working on it now.

**Comment by emeryberger** [comment] 2024-03-10 19:08
Verified that this is now fixed; will be released shortly.

**Closed** 2024-03-10 19:07 UTC
