### ISSUE TITLE
Memory usage not measured everytime

### ISSUE THREAD

**Issue by jose-moralez** [plasma-umass/scalene#156] opened 2021-03-23 21:58 UTC
Hi! Thanks for making this profiler, I think it's awesome.

**Describe the bug**
The profiler sometimes doesn't measure the memory usage.

**To Reproduce**
1. Define `prof_test.py` with the following:
```python
import numpy as np

class A:

    def __init__(self, n):
        self.arr = np.random.rand(n)
        self.lst = [1] * n

if __name__ == '__main__':
    a = A(10_000_000)
```
2. Run scalene from the terminal
```bash
scalene prof_test.py --reduced-profile
```

**Expected behavior**
Show the two allocations for the attributes `arr` and `lst` (approx 75 MB each).

**Screenshots**
This is the expected behaviour:
![image](https://user-images.githubusercontent.com/61287624/112223569-bbd9f480-8bef-11eb-839f-90b7773c3d8f.png)

Sometimes only the time is measured:
![image](https://user-images.githubusercontent.com/61287624/112223522-abc21500-8bef-11eb-899c-a533a0d0acda.png)

Other times only one of the allocations is measured:
![image](https://user-images.githubusercontent.com/61287624/112223479-9d73f900-8bef-11eb-9417-44bf0083794a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Version: 1.3.0

**Comment by emeryberger** [comment] 2021-03-24 16:11
Thanks for the report. I believe this is now fixed in the repository version (you will have to run `make` to rebuild the library, and should be able to try it out with `python3 -m pip install git+https://github.com/plasma-umass/scalene.git`.

**Comment by jose-moralez** [comment] 2021-03-24 16:54
Thanks for the follow up. I just installed the repo version and I'm seeing the same behaviour.

**Comment by emeryberger** [comment] 2021-03-24 17:17
Interesting. For what it's worth, Scalene is a statistical sampler and you shouldn't expect to see exactly the same numbers run after run, but in principle, the variance should be fairly low (by design). Can you see if it stabilizes with a larger `n`?

**Comment by jose-moralez** [comment] 2021-03-24 17:26
Increasing `n` to `100,000,000` (which allocates 760MB for each attribute) still sometimes doesn't show. Are the allocations too fast? I tried increasing `--cpu-sampling-rate` but I believe that doesn't impact the memory profiling, does it?

**Comment by emeryberger** [comment] 2021-03-24 17:33
You can't control the allocation sampling rate -- it's hard-coded (but quasirandom), triggered approximately every 1MB of allocations. If you have one giant allocation (which I believe will happen with the `numpy` call), it's all going to be attributed to one line. (The issue I'd found, for what it's worth, was that two samplers could have inadvertently ended up with the same seed, and this now should be exceedingly unlikely.) What kind of hardware are you running on?

**Comment by jose-moralez** [comment] 2021-03-24 17:42
My use case involves creating many objects and the time profiler works great there. However I've been getting gc warnings so I wanted to get a clearer view of all the allocations happening in the init and in some of the methods to try to address them but I haven't been able to generate the memory profile for them because they don't show the allocations.

<details>
  <summary>Here's the output of lscpu</summary>

  ```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Stepping:                        9
CPU MHz:                         3548.302
CPU max MHz:                     3800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5599.85
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-7
  ```
</details>
Please let me know if you need more information

**Comment by ogrisel** [comment] 2021-03-24 17:48
Funny I was about to report exactly the same issue...

**Comment by emeryberger** [comment] 2021-03-24 18:50
This might be faster over Discord: here's one for Scalene - https://discord.gg/fYbX4Pjd

**Comment by ogrisel** [comment] 2021-03-25 14:08
Here is a simpler reproducer:

```python
import numpy as np
import psutil


a = np.random.rand(10_000_000)
b = np.random.rand(10_000_000)
c = np.random.rand(10_000_000)
a = np.random.rand(10_000_000)
b = np.random.rand(10_000_000)
c = np.random.rand(10_000_000)
a = np.random.rand(10_000_000)
b = np.random.rand(10_000_000)
c = np.random.rand(10_000_000)
a = np.random.rand(10_000_000)
b = np.random.rand(10_000_000)
c = np.random.rand(10_000_000)

used_mem = psutil.Process().memory_info().rss
print(f"Used mem (from psutil): {used_mem/ 1e6:.1f} MB")
```

and here is the report on my machine:

<img width="1188" alt="Screenshot 2021-03-25 at 15 07 30" src="https://user-images.githubusercontent.com/89061/112486116-e1940480-8d7b-11eb-8d67-65ccc7c1b52e.png">

**Comment by ogrisel** [comment] 2021-03-25 14:22
I tried on another machine with linux/x86_64 and get the same problem (numpy also from conda-forge).

I also tried to install numpy with pip (from PyPI.org) and got the same problem. So it's probably not related to the architecture or the compiler.

**Comment by ogrisel** [comment] 2021-03-25 16:54
Based on private discussions, it seems that importing numpy is causing this. For reference here are the threaded runtime libraries initialized when importing numpy on my macos environment:

```
% python -m threadpoolctl -i numpy
[
  {
    "filepath": "/Users/ogrisel/miniforge3/envs/dev/lib/libopenblasp-r0.3.12.dylib",
    "prefix": "libopenblas",
    "user_api": "blas",
    "internal_api": "openblas",
    "version": "0.3.12",
    "num_threads": 8,
    "threading_layer": "openmp"
  },
  {
    "filepath": "/Users/ogrisel/miniforge3/envs/dev/lib/libomp.dylib",
    "prefix": "libomp",
    "user_api": "openmp",
    "internal_api": "openmp",
    "version": null,
    "num_threads": 8
  }
]
```

**Comment by ogrisel** [comment] 2021-03-25 16:54
`libomp` is the OpenMP implementation of LLVM.

**Comment by emeryberger** [comment] 2021-03-27 20:16
This has been fixed in the latest version in the repo; will release a new version to PyPi shortly.

**Closed by emeryberger** 2021-03-27 20:16 UTC

**Comment by ogrisel** [comment] 2021-03-29 08:02
I confirm that it now seems to work as expected:

<img width="1181" alt="Screenshot 2021-03-29 at 10 02 04" src="https://user-images.githubusercontent.com/89061/112805406-d7bd1a80-9075-11eb-99fa-e5004a0fb607.png">

Thanks for the fix!
