### ISSUE TITLE
Unable to Profile CuPy Code

### ISSUE THREAD

**Issue by dreycenfoiles** [plasma-umass/scalene#501] opened 2022-12-04 06:35 UTC
**Describe the bug**
I am unable to use scalene to profile any code that uses [CuPy](https://github.com/cupy/cupy) for GPU programming. When I do, I get the following error: 
```
Error in program being profiled:
 unsupported operand type(s) for /: 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\Users\Dreycen Foiles\Miniconda3\lib\site-packages\scalene\scalene_profiler.py", line 1746, in profile_code
    exec(code, the_globals, the_locals)
  File "test.py", line 3, in <module>
    A = cp.zeros((10, 10, 10))
  File "C:\Users\Dreycen Foiles\Miniconda3\lib\site-packages\cupy\_creation\basic.py", line 211, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "C:\Users\Dreycen Foiles\Miniconda3\lib\site-packages\scalene\scalene_profiler.py", line 817, in cpu_signal_handler
    (gpu_load, gpu_mem_used) = Scalene.__gpu.get_stats()
  File "C:\Users\Dreycen Foiles\Miniconda3\lib\site-packages\scalene\scalene_gpu.py", line 114, in get_stats
    mem_used = self.gpu_memory_usage(self.__pid)
  File "C:\Users\Dreycen Foiles\Miniconda3\lib\site-packages\scalene\scalene_gpu.py", line 107, in gpu_memory_usage
    total_used_GPU_memory += proc.usedGpuMemory / 1048576
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**To Reproduce**
Any code that uses CuPy arrays. To generate the above error, I used the following:
```Python
import cupy as cp 

A = cp.zeros((10, 10, 10))
```

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: MS Edge
 - Version: 107
 
**Expected Behavior**
Scalene should successfully complete a profile of the code.

**Comment by emeryberger** [comment] 2022-12-04 17:51
Can you provide the output of this command? `nvidia-smi`

**Comment by emeryberger** [comment] 2022-12-04 18:06
Cannot reproduce with `cupy-cuda11x` (`Driver Version: 520.61.05    CUDA Version: 11.8`).

**Comment by emeryberger** [comment] 2022-12-04 18:10
Workaround added in https://github.com/plasma-umass/scalene/commit/c1aa3cb47e2650ac6d482013acc9ec5107ac631e. However, I believe the real fix is to use a more recent NVIDIA driver.

**Comment by dreycenfoiles** [comment] 2022-12-04 19:29
> Can you provide the output of this command? `nvidia-smi`

Here is the output

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.06       Driver Version: 522.06       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   35C    P8    N/A /  90W |    460MiB /  4096MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by emeryberger** [comment] 2022-12-06 18:28
Please try again (freshly updated).

**Comment by emeryberger** [comment] 2022-12-09 01:34
Now in new release (1.5.16). Closing because I believe this is now fixed; please let us know one way or the other!

**Closed by emeryberger** 2022-12-09 01:34 UTC

**Comment by dreycenfoiles** [comment] 2022-12-13 10:10
This is working for me now. Thank you very much for the help!
