### ISSUE TITLE
Unsupported 16-bit Application error on Windows 10

### ISSUE THREAD

**Issue by IGRACH** [plasma-umass/scalene#490] opened 2022-11-14 16:06 UTC
I'm getting this error when I run `scalene test.py`. After that popup it returns error in cmd.

Python 3.11.0
scalene 1 .5.14 installed via pip.
Windows 10; 21H2 OS Build 19044.2194

![image](https://user-images.githubusercontent.com/7463331/201707453-0586c357-6a8d-439a-bb29-4b6765e19248.png)

**Comment by emeryberger** [comment] 2022-11-14 21:52
Just installed with Python 3.10, Windows 11, can't reproduce. Please try installing from the repo (`python3 -m pip install git+https://github.com/plasma-umass/scalene`).

**Comment by emeryberger** [comment] 2022-11-16 15:12
Closing since I can't reproduce. Please uninstall, reinstall with the new version, and let us know if the situation persists.

**Closed by emeryberger** 2022-11-16 15:12 UTC

**Comment by IGRACH** [comment] 2022-11-16 15:54
It appears to be working.

Thanks xD
