### ISSUE TITLE
scalene forks itself and does not return to prompt

### ISSUE THREAD

**Issue by cyberic99** [plasma-umass/scalene#289] opened 2021-10-22 13:14 UTC
**Describe the bug**
Hi,
I am trying to use scalene on archlinux

when trying it even on a tiny script, I do not get the prompt back, and scalene creates a huge recursive process tree:
```
2669133 pts/3    S+     0:00          |       |   |   \_ /usr/bin/python /usr/bin/scalene --off p.py
2669134 pts/3    S+     0:00          |       |   |       \_ python -m scalene --off p.py
2669135 pts/3    S+     0:00          |       |   |           \_ python -m scalene --off p.py
2669136 pts/3    S+     0:00          |       |   |               \_ python -m scalene --off p.py
2669137 pts/3    S+     0:00          |       |   |                   \_ python -m scalene --off p.py
2669138 pts/3    S+     0:00          |       |   |                       \_ python -m scalene --off p.py
2669139 pts/3    S+     0:00          |       |   |                           \_ python -m scalene --off p.py
2669140 pts/3    S+     0:00          |       |   |                               \_ python -m scalene --off p.py
2669141 pts/3    S+     0:00          |       |   |                                   \_ python -m scalene --off p.py
2669142 pts/3    S+     0:00          |       |   |                                       \_ python -m scalene --off p.py
2669143 pts/3    S+     0:00          |       |   |                                           \_ python -m scalene --off p.py
2669144 pts/3    S+     0:00          |       |   |                                               \_ python -m scalene --off p.py
2669145 pts/3    S+     0:00          |       |   |                                                   \_ python -m scalene --off p.py
2669146 pts/3    S+     0:00          |       |   |                                                       \_ python -m scalene --off p.py
2669147 pts/3    S+     0:00          |       |   |                                                           \_ python -m scalene --off p.py
2669148 pts/3    S+     0:00          |       |   |                                                               \_ python -m scalene --off p.py
2669149 pts/3    S+     0:00          |       |   |                                                                   \_ python -m scalene --off p.py
2669150 pts/3    S+     0:00          |       |   |                                                                       \_ python -m scalene --off p.py
2669151 pts/3    S+     0:00          |       |   |                                                                           \_ python -m scalene --off p.py
2669153 pts/3    S+     0:00          |       |   |                                                                               \_ python -m scalene --off p.py
2669154 pts/3    S+     0:00          |       |   |                                                                                   \_ python -m scalene --off p.py
2669155 pts/3    S+     0:00          |       |   |                                                         
```

**To Reproduce**

Here is my script:
```shell
$ cat p.py 
#!/bin/python
print("hello")
```

I launch:
scalene --off p.py

if I hit ctrl+c, I sometimes get a traceback, but it seems different everytime:

```python
$ scalene --off p.py
^CTraceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/usr/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 22, in <module>
    import inspect
  File "/usr/lib/python3.9/inspect.py", line 35, in <module>
    import ast
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 978, in get_code
  File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode
KeyboardInterrupt

$ scalene --off p.py
^C[eric@pc-eric tmp]$ scalene --off p.py
^CTraceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/scalene/__main__.py", line 4, in <module>
    from scalene import scalene_profiler
  File "/usr/lib/python3.9/site-packages/scalene/scalene_profiler.py", line 66, in <module>
    from scalene.scalene_output import ScaleneOutput
  File "/usr/lib/python3.9/site-packages/scalene/scalene_output.py", line 8, in <module>
    from rich.console import Console
  File "/home/eric/.local/lib/python3.9/site-packages/rich/console.py", line 31, in <module>
    from . import errors, themes
  File "/home/eric/.local/lib/python3.9/site-packages/rich/themes.py", line 1, in <module>
    from .default_styles import DEFAULT_STYLES
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap>", line 535, in _init_module_attrs
KeyboardInterrupt

$ scalene --off p.py
^CFatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.9/site.py", line 589, in <module>
    main()
  File "/usr/lib/python3.9/site.py", line 575, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.9/site.py", line 316, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/usr/lib/python3.9/site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.9/site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/importlib/util.py", line 2, in <module>
    from . import abc
  File "/usr/lib/python3.9/importlib/abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "/usr/lib/python3.9/typing.py", line 23, in <module>
    import contextlib
  File "/usr/lib/python3.9/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/lib/python3.9/functools.py", line 429, in <module>
    _CacheInfo = namedtuple("CacheInfo", ["hits", "misses", "maxsize", "currsize"])
  File "/usr/lib/python3.9/collections/__init__.py", line 431, in namedtuple
    __new__ = eval(code, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt

```

OS:
archlinux
Python 3.9.7
Scalene version 1.3.16 (compiled from git)

**Comment by emeryberger** [comment] 2022-01-09 23:47
Closing since cannot reproduce.

**Closed by emeryberger** 2022-01-09 23:47 UTC
