### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by themanifold** [plasma-umass/scalene#227] opened 2021-06-17 15:03 UTC
I'm getting the following exception:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/app/venv/lib/python3.8/site-packages/scalene/scalene_sigqueue.py", line 36, in run
    self.process(*item)
  File "/home/app/venv/lib/python3.8/site-packages/scalene/scalene_profiler.py", line 579, in cpu_sigqueue_processor
    output.output_profiles(
  File "/home/app/venv/lib/python3.8/site-packages/scalene/scalene_output.py", line 573, in output_profiles
    fn_stats = stats.build_function_stats(fname)
  File "/home/app/venv/lib/python3.8/site-packages/scalene/scalene_statistics.py", line 196, in build_function_stats
    for line_no in self.function_map[filename]:
RuntimeError: dictionary changed size during iteration
```
I get this from running my long running sanic python web server with the following flags:
```
scalene --profile-interval 5 --outfile /tmp/test.html --reduced-profile --profile-all --html foo.py
```
scalene version: 1.3.6

**Comment by jaltmayerpizzorno** [comment] 2021-07-07 14:31
Hi @themanifold, could you try upgrading to the latest version (1.3.8) to confirm the issue is still there?

**Comment by themanifold** [comment] 2021-07-07 14:48
@jaltmayerpizzorno the problem is that this only happened once. Is there a particular fix that you expect to have solve this?

**Comment by jaltmayerpizzorno** [comment] 2021-07-07 15:11
Yes, I'm not entirely down that rabbit hole yet, but possibly commit fe1bd00dff7c542d4122ffcb30196830c60dd688 .

**Comment by jaltmayerpizzorno** [comment] 2021-07-07 15:14
I'll still try to reproduce the issue, but please upgrade to the latest (1.3.8), to facilitate the bug search.

**Comment by jaltmayerpizzorno** [comment] 2021-07-11 23:22
Closing for lack of evidence of an issue. @themanifold , please re-open if needed.

**Closed by jaltmayerpizzorno** 2021-07-11 23:22 UTC
