### ISSUE TITLE
Scalene is completely broken on my system.

### ISSUE THREAD

**Issue by relt-1** [plasma-umass/scalene#540] opened 2023-01-07 13:51 UTC
**Describe the bug**
When trying to profile my project, it waits a bit, then outputs this and exits.
```
Error in program being profiled:
 maximum recursion depth exceeded while calling a Python object
Scalene: Program did not run for long enough to profile.
```
The project by itself works fine, and other profilers (like Palanteer) work as they should.
**To Reproduce**
0. Use Python 3.11.1 and Windows 11
1. Create a script named `file.py` with only
```
import numpy as np
```
2. Do `scalene file.py`
Program will say that a maximum recursion depth has been exceeded.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Scalene version: repository version
 - Python version: 3.11.1

**Comment by emeryberger** [comment] 2023-01-09 21:38
Cannot reproduce, same command line, same code, same versions (Win 11, Python 3.11.1). Please try re-installing Scalene, and optionally, Python.

**Comment by ThirVondukr** [comment] 2023-01-13 08:43
I encountered the same problem
- OS: Windows 10
- Python: 3.11.1
- Scalene: 1.5.19 (2023.01.06)

Code:
```py
def main():
    i = 0
    for _ in range(100_000_000):
        i += 1
    return i


if __name__ == "__main__":
    print(main())
```
```bash
$ where scalene
.venv\Scripts\scalene.exe

$ scalene test.py
Error in program being profiled:
 maximum recursion depth exceeded while calling a Python object
Scalene: Program did not run for long enough to profile.
```

**Comment by relt-1** [comment] 2023-01-13 08:46
I dont know what could cause my issue, is there a verbose mode or logs i could send?

**Comment by ThirVondukr** [comment] 2023-01-13 08:47
I tested versions from `1.5.15` to `1.5.19`, `1.5.15`-`1.5.16` work as expected, but any later versions don't, producing the same error.

**Comment by colonetti** [comment] 2023-01-15 04:19
I'm getting a similar error:

Error in program being profiled:
 maximum recursion depth exceeded
Scalene: Program did not run for long enough to profile.

OS: Windows 11
Python: 3.11.1
Scalene: 1.5.19 (2023.01.06)

**Comment by sternj** [comment] 2023-01-16 01:13
Successfully replicated on Windows 10 with Python 3.11.1 on `v1.5.19`

**Comment by sternj** [comment] 2023-01-16 01:53
[A traceback](https://gist.github.com/sternj/ad3fb2dc1d685322b1fee49a0930acbe)

**Comment by relt-1** [comment] 2023-01-16 05:58
> I tested versions from `1.5.15` to `1.5.19`, `1.5.15`-`1.5.16` work as expected, but any later versions don't, producing the same error.

1.15.16 also works for me.

**Comment by sternj** [comment] 2023-01-16 20:08
I've tracked down the issue, it seems like `sysconfig.get_path` behaves strangely on Windows. I'm seeing if there's any precedent for this.

**Comment by sternj** [comment] 2023-01-16 20:34
Folks, if y'all wouldn't mind giving PR #548 (branch `fix_issue_540`) a shot to see if it fixes the issue, that would be great!

**Comment by colonetti** [comment] 2023-01-16 20:56
> Folks, if y'all wouldn't mind giving PR #548 (branch `fix_issue_540`) a shot to see if it fixes the issue, that would be great!

It's now working for me. Thanks!

**Comment by sternj** [comment] 2023-01-17 01:56
My theory was wrong! @colonetti  (and others) would you please give it a try again?

**Comment by colonetti** [comment] 2023-01-17 18:37
> My theory was wrong! @colonetti (and others) would you please give it a try again?

Hey, sternj

Just gave it another try and it seems to be working.

Full disclosure: this is my first time using scalene, so I'm still getting to know the tool

Anyways, this is the html file that I get by running "scalene main_script.py":

![image](https://user-images.githubusercontent.com/22954908/212982822-ce0915ee-3416-4860-8090-a3f7fe7b51af.png)

let me know if you need more details to close this issue

**Closed** 2023-01-18 00:53 UTC

**Comment by Anthony-J-G** [comment] 2023-02-23 20:18
Hey all, just wanted to let you guys know that I encountered this same issue yesterday, I'm on Scalene version 1.5.19, Windows 10.0.19044, and working in a Python venv running 3.11.0. Not sure if I'm just not up to date with a current Scalene version that has the fix since it's so recent, but I've tried re-installing/upgrading the software with pip. I love Scalene and have used it in the past, but at the moment it has been rendered completely useless since even the test notebook/examples bring up the issue.

**Comment by emeryberger** [comment] 2023-02-23 20:32
Please try running 3.11.1; there is a known problem with 3.11.0. Also, please go ahead and install the repo version and let us know how that goes: `python3 -m pip install git+https://github.com/plasma-umass/scalane`.

**Comment by sternj** [comment] 2023-02-23 20:37
Confirming-- because of [a bug in CPython's frame reclamation process in 3.11.0,](https://github.com/python/cpython/issues/99729) we will never be able to support it.

**Comment by emeryberger** [comment] 2023-02-23 20:55
Just verified that everything appears to be working fine with both the latest release (1.5.19) and the repo version of Scalene, Python 3.11.2 (latest version), Windows 11, all on ARM (which shouldn't matter).

**Comment by Anthony-J-G** [comment] 2023-02-23 21:05
Thanks so much for the quick response! I tried it twice on 3.11.1 and still ran into the same problem with Scalene 1.5.19, Upgrading to 3.11.2 now.

**Comment by sternj** [comment] 2023-02-23 21:11
This fix is also not in v1.5.19, you could install from source (`pip3 install git+https://github.com/plasma-umass/scalene.git`, if I recall the exact incantation) or we could push up a release

**Comment by Anthony-J-G** [comment] 2023-02-23 21:17
Can confirm that Python 3.11.2, pip install from the repo (which pip freeze calls 1.5.19 so sorry for the confusion), and Windows 10.0.19044 works! Thank you guys so much. Side note: did I miss somewhere where the team notes that 3.11.0 remains unsupported? I thought I saw that it was but I could be wrong. If not, is that something that could be included somewhere?

**Comment by sternj** [comment] 2023-02-23 21:20
I am confused by the fact that 3.11.1 does not work, especially because issues with Windows are unrelated to frame reclamation, but I'm glad it works on 3.11.2!

**Comment by emeryberger** [comment] 2023-02-25 00:23
The repo version should prevent setup on 3.11.0. It's mystifying that it's misbehaving on 3.11.1 and working on 3.11.2, though...
